chaos/powerman

config/ac_snmppower.m4
snmppower/Makefile.am

libsnmp goes away in RHEL7.  It turns out libnetsnmp was there in RHEL6.
Presumably we've been linking against a deprecated library name since
the days when the netsnmp project changed its name.
Thanks to bacaldwell for providing this fix back in Jan 28 2015.

build: use -lnetsnmp not -lsnmp (TOSS-2815)

---

etc/Makefile.am
etc/kvm-ssh.dev
etc/kvm.dev

Added dev files for controlling power to virtual machines running on a
KVM (Kernel-based Virtual Machine) hypervisor, kvm.dev for a local
hypervisor and kvm-ssh for a remote hypervisor.

Added KVM dev files.

---

Makefile.am
configure.ac
examples/powerman_el72.spec.in
powerman.spec.in
powermand/parse_lex.l
scripts/Makefile.am
scripts/powerman.service
scripts/tmpfiles.d/powerman.conf.in

Systemd older than 233 doesn't support RuntimeDirectory*
directives and the accepted method for such releases is
to include a file in /usr/lib/tmpfiles.d to create the
[/var]/run/powerman directory.

portability issues for EL 7.2

---

etc/Makefile.am
etc/rancid-cisco-poe.dev

#27 
I threw together a quick-n-dirty dev file to support using rancid (http://www.shrubbery.net/rancid/) for controlling devices using PoE on Cisco switches. I've needed to power-cycle too many of my cameras and PoE Raspberry Pis, and got tired of doing it by hand!
It's not the most elegant thing I have ever written, but it works for me. This could all be done via. direct ssh/telnet to the Cisco device, but I figured I would let rancid take care of the connection negotiation just to keep it simpler.
It should be straight forward to adapt this for any other managed switch that supports PoE and rancid.

Added rancid Cisco PoE control dev file

---

configure.ac
etc/Makefile.am
etc/openbmc.dev
httppower/httppower.c
man/httppower.8.in
test/Makefile.am
test/README
test/dli.c
test/openbmc-httppower.c
test/t61
test/t61.conf.in
test/t61.exp

This is a very simple support of openbmc with httppower.  It's supported like this:
```
include "/etc/powerman/openbmc.dev"
device "openbmc0" "openbmc" "httppower -u https://pnode0 -H Content-Type:application/json -c |&"
device "openbmc1" "openbmc" "httppower -u https://pnode1 -H Content-Type:application/json -c |&"
device "openbmc2" "openbmc" "httppower -u https://pnode2 -H Content-Type:application/json -c |&"
device "openbmc3" "openbmc" "httppower -u https://pnode3 -H Content-Type:application/json -c |&"
device "openbmc4" "openbmc" "httppower -u https://pnode4 -H Content-Type:application/json -c |&"
node "node0" "openbmc0" "pnode0"
node "node1" "openbmc1" "pnode1"
node "node2" "openbmc2" "pnode2"
node "node3" "openbmc3" "pnode3"
node "node4" "openbmc4" "pnode4"
```
While working on …

Add basic support for openbmc w/ httppower

---

config/systemd.m4

As noted in #37, travis-ci seems to be broken, failing on the `distcheck` target.
I'm not sure if this ever worked or what, but the systemd m4 macro is the same one we used in flux-core, and over there we fixed a bug that seems applicable here, so pull it in.

build: don't install systemd unit file outside of prefix

---

TODO
etc/powerman.conf.example
man/powerman.conf.5.in
powermand/client.c
powermand/parse_lex.l
powermand/parse_tab.y
powermand/parse_util.c
powermand/parse_util.h

Introduce a new optional config file parameter, "log_on_off", a string
which specifies a syslog facility.priority pair as used with the
"logger" utility.
If log_on_off is set, node state changes (on/off/cycle/reset) are logged to syslog
using the specified facility.priority.
Fixes #29

log state changes to syslog

---

configure.ac
etc/redfish.dev
test/Makefile.am
test/redfish-httppower.c
test/t62
test/t62.conf.in
test/t62.exp

This adds basic redfish to powerman, its very similar to the openbmc support that I added previously.  Similar issues that exist with openbmc exist here.

add redfish support

---

.github/workflows/main.yml

Problem: empty github workflow failed.
Error : .github#L1
No event triggers defined in `on`
Add a valid, minimal workflow.

ci: add dummy workflow

---

.github/workflows/main.yml

Problem: previous attempt at dummy github workflow failed.
Error : .github#L1
every step must define a `uses` or `run` key
Try again with run key defined.

ci: try again for minimal dummy workflow

---

config/ax_compiler_vendor.m4
configure.ac
httppower/Makefile.am
libcommon/Makefile.am
liblsd/Makefile.am
liblsd/hostlist.c
libpowerman/Makefile.am
plmpower/Makefile.am
powerman/Makefile.am
powermand/Makefile.am
powermand/parse_lex.l
redfishpower/Makefile.am
snmppower/Makefile.am
test/Makefile.am
test/ilom.c
test/lom.c
test/vpcd.c

This PR fixes all known compiler warnings and re-enables `-Wall -Werror` so we catch future ones in CI.
It also enables automake "maintainer mode", because that's handy.

require warning-free compilation

---

powermand/client.c

I encountered a **misleading-indentation** error when running `make` on three separate Rocky Linux 9.1 servers. I guess it _might_ affect el9 in general but I can't confirm. It's an incredibly trivial fix of enclosing the if statement on line 1070 in `powermand/client.c` in curly-braces. The error occurs when trying to build powermand:
**Steps to reproduce:**
```
chmod +x autogen.sh
./autogen.sh
make
```
```
Making all in powermand
make[1]: Entering directory '/home/paisley/powerman/powermand'
CC       arglist.o
CC       client.o
client.c: In function ‘cli_pre_poll’:
client.c:1070:9: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
1070 |         if (listen_fds[i] != NO_FD)
|         ^~
client.c:1072:13: note: ...this statement, but the latter is misleadingly …
```

Fix misleading-indentation error when running make on RHEL9

---

.github/workflows/main.yml
test/t49
test/t49.conf.in

Problem: tests t48 and t49 use the port 10103 and
will conflict if run at the same time.
Change t49 to use port 10104.
Fixes part of #63

testsuite: fix parallel make failure

---

redfishpower/redfishpower.c

Problem: When issuing a power command, checks are done to ensure paths are setup, but not post data.  If the latter is not set, it can lead to a segfault.
Add check for post data.

redfishpower: check for post data

---

etc/redfishpower-cray-windom.dev

Problem: The cycle_ranged logic in redfishpower-cray-windom.dev is backwards, issuing an "on" before an "off".  It should be the other way around.
Solution: Perform an off and then an on for cycle_ranged.
Fixes #69

etc: fix logic error in redfishpower cray windom

---

test/Makefile.am
test/t63.conf.in

Problem: redfishpower was inadvertently not tested because the test
configuration copy and pasted "ipmipower" and never changed it.
Update test to use redfishpower instead of ipmipower.

test: fix redfishpower tests

---

config/ac_genders.m4
config/ac_httppower.m4
config/ac_pkgconfig.m4
config/ac_redfishpower.m4
config/ac_runas.m4
config/ac_snmppower.m4
config/ac_wrap.m4
configure.ac

Problem: newer autotools warns of obsolete macros and doesn't abort if required bison/flex are not found.
Fix those two things.

build: modernize autoconf, fix bison/flex detection

---

.mergify.yml

Problem: Mergifyio is a nice bot to auto rebase and merge PRs that are approved and have passed all tests.
Add initial mergify support.  Initial reviewers that can approve pull requests are on team @chaos/powerman.  PRs must be tagged with the merge-when-passing label.

.mergify.yml: Add mergify support

---

.mergify.yml

Problem: An approved-reviews-by rule copy and pasted a team from another project.
Update the rule so @chaos/powerman is the set of reviewers for this project.

mergify: fix approved-reviews-by typo

---

src/libcommon/argv.h
src/libcommon/client_proto.h
src/libcommon/debug.h
src/libcommon/error.h
src/libcommon/hprintf.h
src/libcommon/powerman.h
src/libcommon/xmalloc.h
src/libcommon/xpoll.h
src/libcommon/xpty.h
src/libcommon/xread.h
src/libcommon/xregex.h
src/libcommon/xsignal.h
src/libcommon/xtypes.h
src/powerman/arglist.h
src/powerman/client.h
src/powerman/daemon.h
src/powerman/device.h
src/powerman/device_pipe.h
src/powerman/device_private.h
src/powerman/device_serial.h
src/powerman/device_tcp.h
src/powerman/parse_util.h
src/powerman/pluglist.h

Problem: License headers are missing for most project .h header files.
Add license info to header files.

Add license text to header files

---

config/ac_runas.m4
configure.ac
etc/Makefile.am
etc/devices/rancid-edgemax-poe.dev
etc/powerman.service.in

This revives and rebases three single-commit PRs that have been sitting a really long time.  Presumably authors have moved on.  If not, perhaps mentioning the PRs will elicit a response :-)
Really sorry this project was not well maintained during the period of your contribution!  We'll try to do better.
Closes #26
Closes #24
Closes #48

systemd: allow group to be configured and set SHELL in env; add UBNT edge device

---

src/redfishpower/redfishpower.c

Problem: redfisherpower outputs a very generic "node: error" message for all message errors encountered when trying to do a power operation. This isn't that useful.
Check for several error codes specific to "network" or "http" errors to differentiate them from "error", which is now a catch all for every other potential error.

redfishpower: output extra error info

---

man/powerman.1.in
man/powermand.8.in
src/powerman/client.c
src/powerman/client.h
src/powerman/powerman.c
src/powerman/powermand.c
t/t0021-remote-powerman.t

Problem: the powerman client has some odd test options that were used by the previous test harness, and are now unused.
Cull those options.
Ensure `Usage:` output, `powerman(1)`, and `powerman(8)` fully document all options.

cull unused test options and update manual pages

---

configure.ac
man/powerman.1.in
src/plmpower/plmpower.c
src/powerman/powerman.c
src/powerman/powermand.c
t/Makefile.am
t/simulators/baytech.c
t/simulators/cyclades.c
t/simulators/icebox.c
t/simulators/ilom.c
t/simulators/ipmipower.c
t/simulators/lom.c
t/simulators/redfishpower.c
t/simulators/swpdu.c
t/simulators/vpcd.c
t/t0001-powerman-client.t
t/t0004-status-query.t
t/t0006-on-off-cycle.t
t/t0007-temperature.t
t/t0008-beacon.t
t/t0009-reset.t
t/t0010-device-status.t
t/t0011-device-timeout.t
t/t0026-llnl-sierra-cluster.t
t/t0032-list.t

Problem: the powerman client's option parsing is a mess due to the way the test suite used to work.
This removes some options that were "published" before, but they were only added to support the test suite, and I doubt people picked them up and used them as the original options were clearer.  Anyway, perhaps we can just call this out in the next release notes to give people a heads up.

clean up powerman client options

---

configure.ac
etc/Makefile.am
etc/powerman.service.in
etc/tmpfiles.d/powerman.conf.in

Problem: powermand runs as a Type=forking systemd service, but Type=simple is recommended by systemd.service(5).
Switch to Type=simple (the default).
Drop the tmpfiles.d configuration which was for managing /run/powerman on systemd < v233 (now ancient).  Powerman doesn't need the rundir anyway when not running in daemon mode, since all it does is store a pidfile there.
Fixes #13
FWIW I tested this on a debian 12 system and it seems to work fine.

systemd: run as Type=simple

---

src/redfishpower/redfishpower.c

peeling off several commits from multiple other WIP PRs, all minor stuff

redfishpower: minor cleanup

---

src/powerman/device.c

Problem: an assertion failure is seen when powermand tears down with a tcp-connected device:
powermand: device_tcp.c:266: tcp_disconnect:
Assertion `dev->magic == DEV_MAGIC' failed.
This is because dev_destroy sets dev->magic = 0 before it calls dev->disconnect.  When dev->disconnect points to tcp_disconnect() the assertion triggers.
Fixes #106

powermand: fix assertion failure on teardown

---

t/t0026-llnl-sierra-cluster.t

Problem: it is false advertising to have an llnl-sierra-cluster test script that has nothing to do with the record-setting IBM sierra system we that is around today.
Add a clarifying comment to the script.
Fixes #115

testsuite: add clarification to sierra test script

---

src/powerman/parse_tab.y
src/powerman/parse_util.c
src/powerman/powermand.c
t/Makefile.am
t/t0033-valgrind.t

This adds a valgrind test and fixes a few memory leaks but not all of them.The test currently is an expected failure, but it can be run with `-d` and the failures can be picked out of the trash.  I suppose we could merge this as is and pick off the rest of the leaks as time permits.  (I tried but didn't find anything obvious)
```
$ ./t0033-valgrind.t -d
valgrind-3.16.1
ok 1 - create test powerman.conf
not ok 2 - run powermand --stdio under valgrind # TODO known breakage
1..2
$ cat trash-directory.t0033-valgrind/valgrind.err
==27863== Memcheck, a memory error detector
==27863== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==27863== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==27863== Command: …
```

testsuite: add valgrind coverage

---

man/redfishpower.8.in
src/redfishpower/redfishpower.c

Problem: The redfishpower --hostsfile option is oddly included in the project as an option.  The suspicion is it was copy and paste from another project.  The short option for the option is not configured, but the long option is.  It is not documented in --help output, but is oddly documented in the manpage.
Drop the option.
----
I just saw this and was "uuhhhh why is this here"?

redfishpower: remove --hostsfile option

---

src/redfishpower/redfishpower.c

Problem: Some systems return an http 400 error when trying to power on an illegal subsystem.  Redfishpower currently does not handle this error code.
Add handling of error code 400, so we get a nice "bad request" error message.

redfishpower: handle http 400 error

---

src/powerman/client.c
t/etc/valgrind.supp
t/t0033-valgrind.t

This enables the valgrind test added before, with suppressions for liblsd/list.
The issue where `powermand --stdio` would exit immediately when EOF was received on stdin is also fixed.  That was preventing any output from being sent, which is useful to see in test.

enable valgrind test with suppressions

---

src/libcommon/error.c
src/libcommon/error.h
src/powerman/client.c
src/powerman/debug.c
src/powerman/debug.h
src/powerman/device_pipe.c
src/powerman/device_serial.c
src/powerman/device_tcp.c

This tightens up powerman logging and eliminates some unused stuff:
- eliminates unused daemon mode (and -f,--foreground option to disable it)
- eliminates direct syslog logging
- reduces log noise for common events that won't scale to a large number of devices
- apply some file descriptor hygiene that was poorly managed in a recent PR

reduce log noise

---

src/redfishpower/redfishpower.c

Problem: Whenever a power command message struct is created,  it is immediately initialized within curl, which means curl will immediately issue the http request once we enter the primary loop.  This isn't what is desired for "delayed cmds", i.e. status polling that we want to poll at a later time.
This happens to work right now because the only delayed commands we do is status polling.  If the current status polling happens to get the wrong answer, no biggie, we'll try again a second later when we issue the next status poll.  In the future, this will not be the case.  We will want delayed commands to issue their http requests at a later time.
Only initialize curl on a power command once it is added to the active list.
Added a cleanup commit on top.
Side note, I wasn't able to test …

redfishpower: send http request after cmd active

---

etc/devices/redfishpower-cray-r272z30.dev
etc/devices/redfishpower-cray-windom.dev
etc/devices/redfishpower-supermicro.dev
man/redfishpower.8.in
src/redfishpower/redfishpower.c

Per discussion in #148
I think the first and second commit are pretty obvious given the discussion.
Commit number 3 is more debatable.  It would break backwards compatibility if anyone copied/modified an older redfishpower device file.
The primary reason I wanted to go down this path to remove redfishpower "cycle" is b/c parent support (#81) cannot work with native power cycle b/c of the inherent raciness of checking the power status after a power cycle.

redfish: always do off/delay/on for power cycle

---

man/redfishpower.8.in
src/redfishpower/redfishpower.c

splitting off of the big PR as it's rather independent of everything else.
basically the most verbose stuff in redfishpower is output at "level 1" verbosity, which is annoying.  have different levels.

redfishpower: adjust verbosity output

---

man/powerman.dev.5.in
src/redfishpower/redfishpower.c

Problem: When powering on a target, it will sometimes enter the "PoweringOn" state but regress back to the "off" state.  This is likely due to a hardware problem.  It can be hard to diagnose when the only clue is a power on has "timed out".
Add some additional output to help diagnose this situation.
some cleanups added on top

redfishpower: add extra timeout debug information

---

src/redfishpower/redfishpower.c

Problem: When in test mode, the status polling interval is still set to 1 second.  This can slow down tests.
Reduce the status polling interval to 1 millisecond when in test mode.
----
I yoinked a commit from #73 that allows setting the status polling interval for this.

redfishpower: reduce polling interval in test mode

---

etc/devices/appro-gb2.dev
etc/devices/appro-greenblade.dev
etc/devices/swpdu.dev
man/powerman.dev.5.in
src/powerman/device.c
t/simulators/vpcd.c
t/t0004-status-query.t
t/t0007-temperature.t
t/t0008-beacon.t

Problem: When selecting a script to use for an action, the "all" version of a script is always used if the action is a query action (e.g. power status query, beacon query, etc.).
This can be problematic in situations where blades/nodes/etc. are not fully populated, such as in a chassis.  We do not want to query "all" things in that case.
Solution: Only call the "all" script if it is a query and a singlet version of the script does not exist.  For device files where unpopulated nodes may exist, it can define an all script and singlet script for each scenario.
Built on top of #155

powerman: when status and status_all are defined, use status_all only on full pluglist

---

man/redfishpower.8.in
src/libcommon/test/argv.c
src/libcommon/test/xregex.c
src/redfishpower/Makefile.am
src/redfishpower/plugs.c
src/redfishpower/plugs.h
src/redfishpower/redfishpower.c
src/redfishpower/test/plugs.c

Problem: Redfishpower was originally written with only "hosts" in mind, however the correct terminology is for powerman devices
to operate with "plugs".  In most cases, redfishpower "hosts" are simply the same names as the "plugs".
Internally refactor everything to operate on "plugs".  This refactor includes:
- adding a global "plugs" that holds all plugs
- adding a global "plug_map" that maps plugs to hostnames
- initially define all "plugs" to be the same name as the hostnames
- map plug names to hostnames via a new plug2host() function
- all output is based on plugnames instead of hostnames
- rename all functions and variables (e.g. stat_cmd_host() is now stat_cmd_plug()).
----
This PR now precedes #157

redfishpower: refactor internals to use plugs

---

man/redfishpower.8.in
src/redfishpower/redfishpower.c
t/Makefile.am
t/etc/redfishpower-setplugs.dev
t/t0029-redfish.t
t/t0034-redfishpower.t

Problem: In the future it may be convenient to identify hosts
anonymously for easier configuration.  Otherwise, many device
files will have to be created to configure different hosts.
Solution: Support a new setplug config which allows users to map
logical plugs to the indicies of the hosts configured.  For example:
setplugs Node[0-15] [0-15]
This creates a set of plugs named Node[0-15].  These may be used
in place of nodenames input on the command line.
built on top of #156

redfishpower: support setplugs configuration

---

man/redfishpower.8.in
src/redfishpower/Makefile.am
src/redfishpower/plugs.c
src/redfishpower/plugs.h
src/redfishpower/redfishpower.c
src/redfishpower/redfishpower_defs.h
src/redfishpower/test/plugs.c
t/Makefile.am
t/etc/redfishpower-setpath.dev
t/t0034-redfishpower.t

Problem: Currently in redfishpower, a single global setting for
stat, on, off, and cycle paths is configured for all hosts.  This
may not be convenient for some environments, where some specific
hosts need to have different paths for power operations.
Support a new configuration "setpath" that can set paths for
specific hosts.  The remaining configurations remain in place
to configure the "defaults".
Built on top of #157

redfishpower: support setpath configuration 

---

man/redfishpower.8.in
src/redfishpower/redfishpower.c
t/Makefile.am
t/etc/redfishpower-plugsub-blades.dev
t/etc/redfishpower-plugsub.dev
t/t0034-redfishpower.t

Problem: In some chassis, power status/control URIs are all
minorly different from each other when doing power status/control
to blades.  This makes it difficult to configure powerman/redfishpower
for bladed environments.
Solution: Support plug substitution in URIs with the pattern %p.
By using plug names that are the minor variants of each URI, paths
can be easily configured for each blade in a chassis.  This now allows
the setplugs command to map mutiple plug names to a single index.
Fixes #129
Built on top of #158

redfishpower: support plug substitution

---

man/redfishpower.8.in
src/redfishpower/plugs.c
src/redfishpower/plugs.h
src/redfishpower/redfishpower.c
src/redfishpower/test/plugs.c
t/Makefile.am
t/etc/redfishpower-parents-2-levels.dev
t/etc/redfishpower-parents-3-levels.dev
t/t0034-redfishpower.t

Problem: In some hardware, there is a hierarchy for power control.  For example, In bladed systems the chassis must be powered on before blades can be powered on.  Without knowledge of this dependency, power control can become difficult to use.
Solution: Support configuration of hierarchies through an optional "parent" configuration in the "setplugs" option.
With knowledge of hierarchy, support following behavior semantics in redfishpower.
When doing a power operation, check parents/ancestors power status first.
If ancestors are all on, then redfishpower can perform power on/off/status on the target.
If ancestor is off, power status is defined as off for all descendants.  Power on cannot be done.  Power off is assumed to succeed.
As special case, if powering on both ancestors and …

redfishpower: support plug parents

---

src/redfishpower/redfishpower.c
t/t0034-redfishpower.t

TSIA
Note, can be reviewed indepedently of #167 and #168

redfishpower: fix memleaks and test under valgrind

---

src/powerman/device.c
t/etc/vpc.dev
t/simulators/vpcd.c
t/t0006-on-off-cycle.t

Problem: When selecting a script to use for an action (i.e.  power on) powerman may select the "all" or "ranged" script if they are available.  This is done even if a single plug is targeted.  There is nothing wrong with this, but may not be what users expect.
If the user is specifically targeting only one plug, select the singlet script over any other script.

 powerman: use singlet script if targeting one plug

---

src/redfishpower/redfishpower.c

Problem: The status polling interval is hard coded to 1 second long.  This can result in an excessive number of polling messages being sent when it is known that some hardware takes 20-50 seconds to complete a power operation.
Solution: Support a modified "exponential backoff" of the status polling interval.  The modified algorithm is based on observations of how long it typically takes to complete power operations on hardware.  The status polling interval begins at one second, but it gets capped at 4 seconds.

redfishpower: adapt status polling interval

---

src/powerman/client.c
src/powerman/client_proto.h
src/powerman/device.c
src/powerman/device_private.h
src/powerman/powerman.c
t/Makefile.am
t/simulators/vpcd.c
t/t0036-diagnostics.t

Problem: When power control/query to a target fails, there is no way for a user to know why it failed except through the very verbose --telemetry output.
Add a new --diag to powerman that will inform powermand to send diagnostic information about why a power operation failed.  Common errors from the same host will be collapsed into a hostrange.  This only works with setplugstate and the new setresult statement.
```
> pm --diag -1 t[0-15]
t[7,15]: error
Command completed with errors
```

powerman: support error diagnostics with setresult

---

etc/Makefile.am
etc/devices/redfishpower-cray-ex.dev
t/Makefile.am
t/t0037-cray-ex.t

Built on top of #167 and #172, but those don't have to go in first.  #167 is a "pretty nice to have" (would like to have before release), #172 can be debated before release if it should go in.

Add redfishpower HPE Cray EX chassis device file

---

t/Makefile.am
t/t0039-llnl-el-capitan-cluster.t

Following up on #126:  here's a demo of 16K redfish nodes - in groups of 8.
The idea was to simulate a big config with 8-slot blade chassis, one redfish "device" per chassis.  Seems to work fine on my desktop.  I wonder if it'll work in CI?

test a huge cray-ex configuration

---

etc/devices/redfishpower-cray-ex-rabbit.dev
etc/devices/redfishpower-cray-ex.dev

Problem: The default authentication set by the manufactuer is known for Cray EX chassis.  Setting the default would make initial testing with powerman easier for users.
Set the manufacturer default authentication in redfishpower-cray-ex.dev and redfishpower-cray-ex-rabbit.dev.
Fixes #176

etd/devices: set default Cray EX authentication

---

config/ac_httppower.m4
config/ac_redfishpower.m4
config/ac_snmppower.m4

Problem: Some tests now require the helper redfishpower executable. This executable is not built by default, possibly breaking tests.
Build helper executables httppower, snmppower, and redfishpower by default.  Configure options to disable the builds are available.
Fixes #178

configure.ac: build helper executables by default

---

etc/devices/redfishpower-cray-ex-rabbit.dev
etc/devices/redfishpower-cray-ex.dev
etc/devices/redfishpower-cray-r272z30.dev
etc/devices/redfishpower-cray-windom.dev
etc/devices/redfishpower-supermicro.dev
man/redfishpower.8.in
src/redfishpower/redfishpower.c

Problem: It can be inconvenient to configure username/password authentication info with redfishpower, since it can only be done in the device files.
Support a --auth option to configure it on the command line.  This way it can be configured in powerman config files.
Fixes #94

redfishpower: support auth setup on command line

---

src/redfishpower/redfishpower.c

Problem: Redfishpower decided to output a generic "network error" message when either a connection error occurred (i.e. typically if the host is down) vs a operation timeout (i.e. such as a failed DNS lookup).  It would be useful to know which one actually happened.
Split the "network error" message into two specific error messages.

redfishpower: output more detailed error messages

---

man/redfishpower.8.in
src/redfishpower/redfishpower.c
t/t0034-redfishpower.t

Problem: The message timeout is currently hard coded to 5 seconds, which may be too short or long on some systems.
Support a new --message-timeout option to support configuration of the message timeout.

redfishpower: support message timeout config

---

man/redfishpower.8.in
src/redfishpower/redfishpower.c
t/t0034-redfishpower.t

Problem: A DNS race in libcurl exists in versions before 7.66.  This can
lead to redfishpower returning "Timeout was reached".
Support a new --host2ip option which will convert input hostnames to IP
addresses and pass those IP addresses to libcurl.  This appears to work
around the race.
----
Built on top of #186 ... maybe `--host2ip` option name could be better?

redfishpower: support new --resolve-hosts option

---

man/redfishpower.8.in
src/redfishpower/redfishpower.c

Problem: It appears that repeated host resolution lookups slows down redfishpower/powerman at large scales.
Cache previous lookups in a hash.

redfishpower: cache host resolution lookups

---

man/redfishpower.8.in
src/redfishpower/redfishpower.c

Problem: In commit
97449c5f8700990293c0048d6f4b437097102921
the default message timeout was lowered from 10 seconds to 5 seconds. While this is good for the "99%" of cases, it doesn't appear to be good for "99.9% of cases, as some timeouts appear a little more often.
Change the default message timeout back to 10 seconds.

redfishpower: increase default message timeout

---

src/powerman/client_proto.h
t/t0039-llnl-el-capitan-cluster.t

Problem: On very larger clusters command line operations of a large
number of nodes (e.g. node[1,3,5,...,4997,4999]) can exceed internal
buffers, leading to errors.
Increase the internal maximum line length from 8K to 128K, which should
handle any HPC cluster in existence today and larger ones in the future.
Fixes #193
---
side note, for the test I just created the giant input and put it in a file in `t/data` b/c I was not confident that hostlist generating tools that could generate it would exist on many environments. (i.e. reproducer I was shown used `cluset` which I don't think is that common.  Neither would `flux hostlist`, etc.)

powerman: increase maximum line length

---

src/liblsd/hostlist.c
src/liblsd/hostlist.h

Problem: The hostlist library is out of date from the one in pdsh. The one in pdsh includes several fixes, including a fix for an out of bounds array access.
Update hostlist library from current copy in pdsh.

liblsd: update hostlist library

---

src/powerman/device.c
src/redfishpower/redfishpower.c
t/t0037-cray-ex.t

Problem: In _process_setresult() if the plug name is not found in the inputted arglist, it can result in a segfault.  This can occur when power operations on dependent targets (e.g. the parent of node needs to be powered on) have errors, leading to an unexpected host having a "power result".
Check that arg is non-NULL before trying to dereference it.
Fixes #197
---
side note, alternately those types of unexpected error messages could be removed from `redfishpower`.  I elected to leave those error messages.  I figure for telemetry output and debugging, it can still be useful to output "severe error messages" (i.e. http error) on parents

powerman: correct potential segfault

---

src/powerman/device.c

This would avoid build failure due to type mismatch on architecture where 64-bit time_t and %ld printf formatter coexist and -Werror=format is enabled.
This fixes #199.

device.c: Unconditionally cast tv_{sec,usec} to lld for printf

---

etc/powerman.service.in

Problem: this syslog target is deprecated.
Syslog is socket-activated so there is no need to wait for it.
Fixes #203

systemd: drop deprecated After=syslog.target

---

src/redfishpower/redfishpower.c
t/t0034-redfishpower.t

Problem: In test mode, debug for the resolve-hosts option is always output.  This can get annoying.
Only output debug indicating that resolve-hosts is set.  Don't output if it is not set.
Fixes #207

redfishpower: remove excessive debug output

---

.github/workflows/main.yml
t/t0039-llnl-el-capitan-cluster.t

Problem: the debian riscv64 build environment is failing on the el capitan scaling test.
We don't have detailed test output to diagnose the failure but we can probably assume that this is a fairly under-powered builder.
Disable the test unless TEST_LONG is set in the test environment. Set TEST_LONG when the github workflow runs make check, so we won't lose this coverage in github CI.
Fixes #206

testsuite: skip huge test unless requested
